# Generated by Django 4.1.3 on 2022-11-21 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="favourite_by",
            field=models.ManyToManyField(
                db_constraint=[
                    models.UniqueConstraint(
                        fields=("note_id", "user_id"), name="unique_favourites"
                    )
                ],
                related_name="favourite_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
